/**
 * Core inbound email processing pipeline.
 *
 * Orchestrates: spam filter → language detection → dedup check →
 * lead upsert → reply generation → provider-aware send → status update.
 *
 * Outbound sending is provider-aware:
 *   - gmail / outlook / imap providers use their own credentials
 *   - webhook_inbound / resend / unset providers fall back to Resend
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { filterInboundEmail } from './spam-filter';
import { detectEmailLanguage } from './language-detection';
import { generateAutoReply } from './reply-generator';
import { sendEmailViaProvider } from '@/lib/email/providers';
import type {
  InboundEmailEvent,
  ProcessInboundEmailResult,
  EmailAutomationSettings,
} from './types';

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function isValidEmail(email: string | null | undefined): email is string {
  return !!email && EMAIL_RE.test(email.trim());
}

function makeThreadDedupeKey(organizationId: string, event: InboundEmailEvent): string {
  if (event.threadId) return `${organizationId}:thread:${event.threadId}`;
  // Fall back to sender + normalised subject
  const subjectNorm = (event.subject ?? '').toLowerCase().replace(/^re:\s*/g, '').trim().slice(0, 80);
  return `${organizationId}:sender:${event.senderEmail}:${subjectNorm}`;
}

/** Load an email_provider record including config_json (server-side only). */
async function getProviderRecord(
  supabase: SupabaseClient,
  emailProviderId: string | null,
  organizationId: string
): Promise<{ id: string; organization_id: string; provider_type: string; config_json: Record<string, unknown> | null } | null> {
  if (!emailProviderId) return null;

  const { data } = await supabase
    .from('email_providers')
    .select('id, organization_id, provider_type, config_json')
    .eq('id', emailProviderId)
    .eq('organization_id', organizationId)
    .maybeSingle();

  return data as typeof data;
}

async function getOrCreateSettings(
  supabase: SupabaseClient,
  organizationId: string
): Promise<EmailAutomationSettings | null> {
  const { data } = await supabase
    .from('email_automation_settings')
    .select('*')
    .eq('organization_id', organizationId)
    .maybeSingle();
  return (data as EmailAutomationSettings | null) ?? null;
}

async function getBusinessName(
  supabase: SupabaseClient,
  organizationId: string
): Promise<string | null> {
  const { data } = await supabase
    .from('business_settings')
    .select('business_name')
    .eq('organization_id', organizationId)
    .maybeSingle();
  return (data as { business_name: string | null } | null)?.business_name ?? null;
}

async function upsertLead(
  supabase: SupabaseClient,
  organizationId: string,
  event: InboundEmailEvent,
  detectedLanguage: string
): Promise<string | null> {
  // Check if a lead already exists for this sender
  const { data: existing } = await supabase
    .from('leads')
    .select('id')
    .eq('organization_id', organizationId)
    .eq('email', event.senderEmail)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  if (existing?.id) {
    return existing.id as string;
  }

  const { data: newLead } = await supabase
    .from('leads')
    .insert({
      organization_id: organizationId,
      name: event.senderName ?? event.senderEmail,
      email: event.senderEmail,
      message: event.subject
        ? `Email inquiry: ${event.subject}`
        : 'Inbound email inquiry',
      customer_language: detectedLanguage,
    })
    .select('id')
    .maybeSingle();

  return (newLead?.id as string | null) ?? null;
}

export async function processInboundEmail(params: {
  supabase: SupabaseClient;
  organizationId: string;
  emailProviderId: string | null;
  event: InboundEmailEvent;
}): Promise<ProcessInboundEmailResult> {
  const { supabase, organizationId, emailProviderId, event } = params;

  // ── 1. Load automation settings ────────────────────────────────────────────
  const settings = await getOrCreateSettings(supabase, organizationId);

  if (!settings?.enabled) {
    const inboundId = await insertInboundEmail(supabase, {
      organizationId,
      emailProviderId,
      event,
      detectedLanguage: null,
      languageConfidence: null,
      isSpam: false,
      isAutoGenerated: false,
      processingStatus: 'skipped',
      skipReason: 'auto_reply_disabled',
      leadId: null,
    });
    return { status: 'skipped', reason: 'auto_reply_disabled', inboundEmailId: inboundId, autoReplyId: null };
  }

  // ── 2. Spam / no-reply filter ──────────────────────────────────────────────
  const filter = filterInboundEmail({
    senderEmail: event.senderEmail,
    subject: event.subject,
    bodyText: event.bodyText,
    bodyHtml: event.bodyHtml,
  });

  if (filter.shouldSkip) {
    const inboundId = await insertInboundEmail(supabase, {
      organizationId,
      emailProviderId,
      event,
      detectedLanguage: null,
      languageConfidence: null,
      isSpam: filter.isSpam,
      isAutoGenerated: filter.isAutoGenerated,
      processingStatus: 'skipped',
      skipReason: filter.reason,
      leadId: null,
    });
    return { status: 'skipped', reason: filter.reason ?? 'filtered', inboundEmailId: inboundId, autoReplyId: null };
  }

  // ── 3. Language detection ──────────────────────────────────────────────────
  const textForDetection = event.bodyText ?? event.bodyHtml?.replace(/<[^>]+>/g, ' ') ?? '';
  const langResult = await detectEmailLanguage(
    textForDetection,
    settings.fallback_language,
    true
  );

  // ── 4. Deduplication — max replies per thread ──────────────────────────────
  const threadDedupeKey = makeThreadDedupeKey(organizationId, event);
  const { count } = await supabase
    .from('email_auto_replies')
    .select('id', { count: 'exact', head: true })
    .eq('organization_id', organizationId)
    .eq('thread_dedupe_key', threadDedupeKey);

  if ((count ?? 0) >= settings.max_auto_replies_per_thread) {
    const inboundId = await insertInboundEmail(supabase, {
      organizationId,
      emailProviderId,
      event,
      detectedLanguage: langResult.languageCode,
      languageConfidence: langResult.confidence,
      isSpam: false,
      isAutoGenerated: false,
      processingStatus: 'skipped',
      skipReason: 'max_replies_reached',
      leadId: null,
    });
    return { status: 'skipped', reason: 'max_replies_reached', inboundEmailId: inboundId, autoReplyId: null };
  }

  // ── 5. Upsert lead ─────────────────────────────────────────────────────────
  const leadId = await upsertLead(supabase, organizationId, event, langResult.languageCode);

  // ── 6. Save inbound email ──────────────────────────────────────────────────
  const inboundId = await insertInboundEmail(supabase, {
    organizationId,
    emailProviderId,
    event,
    detectedLanguage: langResult.languageCode,
    languageConfidence: langResult.confidence,
    isSpam: false,
    isAutoGenerated: false,
    processingStatus: 'pending',
    skipReason: null,
    leadId,
  });

  // ── 7. Generate reply ──────────────────────────────────────────────────────
  const businessName = await getBusinessName(supabase, organizationId);
  let replyPayload;
  try {
    replyPayload = await generateAutoReply({
      supabase,
      organizationId,
      settings,
      detectedLanguage: langResult.languageCode,
      customerName: event.senderName,
      businessName,
      originalSubject: event.subject,
    });
  } catch (err) {
    await markInboundFailed(supabase, inboundId, 'reply_generation_failed');
    return {
      status: 'failed',
      reason: 'reply_generation_failed',
      inboundEmailId: inboundId,
      autoReplyId: null,
    };
  }

  // ── 8. Insert auto-reply record ────────────────────────────────────────────
  const { data: autoReplyRow } = await supabase
    .from('email_auto_replies')
    .insert({
      organization_id: organizationId,
      inbound_email_id: inboundId,
      lead_id: leadId,
      to_email: event.senderEmail,
      to_name: event.senderName,
      subject: replyPayload.subject,
      body_html: replyPayload.bodyHtml,
      body_text: replyPayload.bodyText,
      reply_language: replyPayload.replyLanguage,
      template_id: replyPayload.templateId,
      ai_enhanced: replyPayload.aiEnhanced,
      status: 'pending',
      thread_dedupe_key: threadDedupeKey,
    })
    .select('id')
    .maybeSingle();

  const autoReplyId = (autoReplyRow?.id as string | null) ?? null;

  // ── 9. Send via provider-aware abstraction ────────────────────────────────
  // Use the inbound provider for sending if it supports outbound (gmail/outlook/imap).
  // Otherwise falls back to Resend automatically.
  const providerRecord = await getProviderRecord(supabase, emailProviderId, organizationId);

  const sendResult = await sendEmailViaProvider(providerRecord, {
    to: event.senderEmail,
    toName: event.senderName,
    subject: replyPayload.subject,
    html: replyPayload.bodyHtml,
    text: replyPayload.bodyText,
    inReplyTo: event.messageId,
    references: [event.messageId, event.inReplyTo].filter((v): v is string => !!v),
  });

  if (!sendResult.success) {
    const errMsg = sendResult.error ?? 'Send failed';
    await Promise.all([
      markInboundFailed(supabase, inboundId, 'send_failed'),
      autoReplyId &&
        supabase
          .from('email_auto_replies')
          .update({ status: 'failed', error_message: errMsg.slice(0, 500) })
          .eq('id', autoReplyId),
    ]);
    return { status: 'failed', reason: errMsg, inboundEmailId: inboundId, autoReplyId };
  }

  const now = new Date().toISOString();
  await Promise.all([
    supabase
      .from('email_auto_replies')
      .update({
        status: 'sent',
        provider: sendResult.provider,
        provider_message_id: sendResult.messageId ?? null,
        sent_at: now,
      })
      .eq('id', autoReplyId ?? ''),
    supabase
      .from('inbound_emails')
      .update({ processing_status: 'replied', processed_at: now })
      .eq('id', inboundId ?? ''),
  ]);

  return { status: 'replied', inboundEmailId: inboundId, autoReplyId };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function insertInboundEmail(
  supabase: SupabaseClient,
  row: {
    organizationId: string;
    emailProviderId: string | null;
    event: InboundEmailEvent;
    detectedLanguage: string | null;
    languageConfidence: number | null;
    isSpam: boolean;
    isAutoGenerated: boolean;
    processingStatus: string;
    skipReason: string | null;
    leadId: string | null;
  }
): Promise<string | null> {
  const { data } = await supabase
    .from('inbound_emails')
    .insert({
      organization_id: row.organizationId,
      email_provider_id: row.emailProviderId,
      sender_email: row.event.senderEmail,
      sender_name: row.event.senderName,
      subject: row.event.subject,
      body_text: row.event.bodyText?.slice(0, 50000) ?? null,
      body_html: row.event.bodyHtml?.slice(0, 100000) ?? null,
      message_id: row.event.messageId,
      in_reply_to: row.event.inReplyTo,
      thread_id: row.event.threadId,
      detected_language: row.detectedLanguage,
      language_confidence: row.languageConfidence,
      is_spam: row.isSpam,
      is_auto_generated: row.isAutoGenerated,
      processing_status: row.processingStatus,
      skip_reason: row.skipReason,
      lead_id: row.leadId,
      received_at: row.event.receivedAt ?? new Date().toISOString(),
    })
    .select('id')
    .maybeSingle();
  return (data?.id as string | null) ?? null;
}

async function markInboundFailed(
  supabase: SupabaseClient,
  inboundId: string | null,
  reason: string
): Promise<void> {
  if (!inboundId) return;
  await supabase
    .from('inbound_emails')
    .update({ processing_status: 'failed', skip_reason: reason, processed_at: new Date().toISOString() })
    .eq('id', inboundId);
}
