/**
 * Core inbound email processing pipeline.
 *
 * Orchestrates: spam filter → language detection → dedup check →
 * lead upsert → reply generation → reply send → status update.
 */

import { Resend } from 'resend';
import type { SupabaseClient } from '@supabase/supabase-js';
import { filterInboundEmail } from './spam-filter';
import { detectEmailLanguage } from './language-detection';
import { generateAutoReply } from './reply-generator';
import type {
  InboundEmailEvent,
  ProcessInboundEmailResult,
  EmailAutomationSettings,
} from './types';

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function isValidEmail(email: string | null | undefined): email is string {
  return !!email && EMAIL_RE.test(email.trim());
}

function getFromEmail(): string {
  const rawFrom = process.env.RESEND_FROM_EMAIL ?? '';
  const freeEmailDomains = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'live.com', 'icloud.com'];
  const fromDomain = rawFrom.includes('@') ? rawFrom.split('@')[1]?.toLowerCase() : '';
  const isFreeEmail = freeEmailDomains.some(
    (d) => fromDomain === d || fromDomain?.endsWith('.' + d)
  );
  return rawFrom && !isFreeEmail ? rawFrom : 'Spaxio Assistant <onboarding@resend.dev>';
}

function makeThreadDedupeKey(organizationId: string, event: InboundEmailEvent): string {
  if (event.threadId) return `${organizationId}:thread:${event.threadId}`;
  // Fall back to sender + normalised subject
  const subjectNorm = (event.subject ?? '').toLowerCase().replace(/^re:\s*/g, '').trim().slice(0, 80);
  return `${organizationId}:sender:${event.senderEmail}:${subjectNorm}`;
}

async function getOrCreateSettings(
  supabase: SupabaseClient,
  organizationId: string
): Promise<EmailAutomationSettings | null> {
  const { data } = await supabase
    .from('email_automation_settings')
    .select('*')
    .eq('organization_id', organizationId)
    .maybeSingle();
  return (data as EmailAutomationSettings | null) ?? null;
}

async function getBusinessName(
  supabase: SupabaseClient,
  organizationId: string
): Promise<string | null> {
  const { data } = await supabase
    .from('business_settings')
    .select('business_name')
    .eq('organization_id', organizationId)
    .maybeSingle();
  return (data as { business_name: string | null } | null)?.business_name ?? null;
}

async function upsertLead(
  supabase: SupabaseClient,
  organizationId: string,
  event: InboundEmailEvent,
  detectedLanguage: string
): Promise<string | null> {
  // Check if a lead already exists for this sender
  const { data: existing } = await supabase
    .from('leads')
    .select('id')
    .eq('organization_id', organizationId)
    .eq('email', event.senderEmail)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  if (existing?.id) {
    return existing.id as string;
  }

  const { data: newLead } = await supabase
    .from('leads')
    .insert({
      organization_id: organizationId,
      name: event.senderName ?? event.senderEmail,
      email: event.senderEmail,
      message: event.subject
        ? `Email inquiry: ${event.subject}`
        : 'Inbound email inquiry',
      customer_language: detectedLanguage,
    })
    .select('id')
    .maybeSingle();

  return (newLead?.id as string | null) ?? null;
}

export async function processInboundEmail(params: {
  supabase: SupabaseClient;
  organizationId: string;
  emailProviderId: string | null;
  event: InboundEmailEvent;
}): Promise<ProcessInboundEmailResult> {
  const { supabase, organizationId, emailProviderId, event } = params;

  // ── 1. Load automation settings ────────────────────────────────────────────
  const settings = await getOrCreateSettings(supabase, organizationId);

  if (!settings?.enabled) {
    const inboundId = await insertInboundEmail(supabase, {
      organizationId,
      emailProviderId,
      event,
      detectedLanguage: null,
      languageConfidence: null,
      isSpam: false,
      isAutoGenerated: false,
      processingStatus: 'skipped',
      skipReason: 'auto_reply_disabled',
      leadId: null,
    });
    return { status: 'skipped', reason: 'auto_reply_disabled', inboundEmailId: inboundId, autoReplyId: null };
  }

  // ── 2. Spam / no-reply filter ──────────────────────────────────────────────
  const filter = filterInboundEmail({
    senderEmail: event.senderEmail,
    subject: event.subject,
    bodyText: event.bodyText,
    bodyHtml: event.bodyHtml,
  });

  if (filter.shouldSkip) {
    const inboundId = await insertInboundEmail(supabase, {
      organizationId,
      emailProviderId,
      event,
      detectedLanguage: null,
      languageConfidence: null,
      isSpam: filter.isSpam,
      isAutoGenerated: filter.isAutoGenerated,
      processingStatus: 'skipped',
      skipReason: filter.reason,
      leadId: null,
    });
    return { status: 'skipped', reason: filter.reason ?? 'filtered', inboundEmailId: inboundId, autoReplyId: null };
  }

  // ── 3. Language detection ──────────────────────────────────────────────────
  const textForDetection = event.bodyText ?? event.bodyHtml?.replace(/<[^>]+>/g, ' ') ?? '';
  const langResult = await detectEmailLanguage(
    textForDetection,
    settings.fallback_language,
    true
  );

  // ── 4. Deduplication — max replies per thread ──────────────────────────────
  const threadDedupeKey = makeThreadDedupeKey(organizationId, event);
  const { count } = await supabase
    .from('email_auto_replies')
    .select('id', { count: 'exact', head: true })
    .eq('organization_id', organizationId)
    .eq('thread_dedupe_key', threadDedupeKey);

  if ((count ?? 0) >= settings.max_auto_replies_per_thread) {
    const inboundId = await insertInboundEmail(supabase, {
      organizationId,
      emailProviderId,
      event,
      detectedLanguage: langResult.languageCode,
      languageConfidence: langResult.confidence,
      isSpam: false,
      isAutoGenerated: false,
      processingStatus: 'skipped',
      skipReason: 'max_replies_reached',
      leadId: null,
    });
    return { status: 'skipped', reason: 'max_replies_reached', inboundEmailId: inboundId, autoReplyId: null };
  }

  // ── 5. Upsert lead ─────────────────────────────────────────────────────────
  const leadId = await upsertLead(supabase, organizationId, event, langResult.languageCode);

  // ── 6. Save inbound email ──────────────────────────────────────────────────
  const inboundId = await insertInboundEmail(supabase, {
    organizationId,
    emailProviderId,
    event,
    detectedLanguage: langResult.languageCode,
    languageConfidence: langResult.confidence,
    isSpam: false,
    isAutoGenerated: false,
    processingStatus: 'pending',
    skipReason: null,
    leadId,
  });

  // ── 7. Generate reply ──────────────────────────────────────────────────────
  const businessName = await getBusinessName(supabase, organizationId);
  let replyPayload;
  try {
    replyPayload = await generateAutoReply({
      supabase,
      organizationId,
      settings,
      detectedLanguage: langResult.languageCode,
      customerName: event.senderName,
      businessName,
      originalSubject: event.subject,
    });
  } catch (err) {
    await markInboundFailed(supabase, inboundId, 'reply_generation_failed');
    return {
      status: 'failed',
      reason: 'reply_generation_failed',
      inboundEmailId: inboundId,
      autoReplyId: null,
    };
  }

  // ── 8. Insert auto-reply record ────────────────────────────────────────────
  const { data: autoReplyRow } = await supabase
    .from('email_auto_replies')
    .insert({
      organization_id: organizationId,
      inbound_email_id: inboundId,
      lead_id: leadId,
      to_email: event.senderEmail,
      to_name: event.senderName,
      subject: replyPayload.subject,
      body_html: replyPayload.bodyHtml,
      body_text: replyPayload.bodyText,
      reply_language: replyPayload.replyLanguage,
      template_id: replyPayload.templateId,
      ai_enhanced: replyPayload.aiEnhanced,
      status: 'pending',
      thread_dedupe_key: threadDedupeKey,
    })
    .select('id')
    .maybeSingle();

  const autoReplyId = (autoReplyRow?.id as string | null) ?? null;

  // ── 9. Send via Resend ─────────────────────────────────────────────────────
  const resendKey = process.env.RESEND_API_KEY;
  if (!resendKey) {
    await Promise.all([
      markInboundFailed(supabase, inboundId, 'resend_key_missing'),
      autoReplyId &&
        supabase
          .from('email_auto_replies')
          .update({ status: 'failed', error_message: 'RESEND_API_KEY not configured' })
          .eq('id', autoReplyId),
    ]);
    return { status: 'failed', reason: 'email_provider_not_configured', inboundEmailId: inboundId, autoReplyId };
  }

  try {
    const resend = new Resend(resendKey);
    const sent = await resend.emails.send({
      from: getFromEmail(),
      to: [event.senderEmail],
      subject: replyPayload.subject,
      html: replyPayload.bodyHtml,
      text: replyPayload.bodyText,
      headers: {
        'In-Reply-To': event.messageId ?? '',
        References: [event.messageId, event.inReplyTo].filter(Boolean).join(' '),
        'X-Auto-Response-Suppress': 'All',
        'Auto-Submitted': 'auto-replied',
      },
    });

    const now = new Date().toISOString();
    await Promise.all([
      supabase
        .from('email_auto_replies')
        .update({
          status: 'sent',
          provider: 'resend',
          provider_message_id: sent.data?.id ?? null,
          sent_at: now,
        })
        .eq('id', autoReplyId ?? ''),
      supabase
        .from('inbound_emails')
        .update({ processing_status: 'replied', processed_at: now })
        .eq('id', inboundId ?? ''),
    ]);

    return { status: 'replied', inboundEmailId: inboundId, autoReplyId };
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : 'Send failed';
    await Promise.all([
      markInboundFailed(supabase, inboundId, 'send_failed'),
      autoReplyId &&
        supabase
          .from('email_auto_replies')
          .update({ status: 'failed', error_message: errMsg.slice(0, 500) })
          .eq('id', autoReplyId),
    ]);
    return { status: 'failed', reason: errMsg, inboundEmailId: inboundId, autoReplyId };
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function insertInboundEmail(
  supabase: SupabaseClient,
  row: {
    organizationId: string;
    emailProviderId: string | null;
    event: InboundEmailEvent;
    detectedLanguage: string | null;
    languageConfidence: number | null;
    isSpam: boolean;
    isAutoGenerated: boolean;
    processingStatus: string;
    skipReason: string | null;
    leadId: string | null;
  }
): Promise<string | null> {
  const { data } = await supabase
    .from('inbound_emails')
    .insert({
      organization_id: row.organizationId,
      email_provider_id: row.emailProviderId,
      sender_email: row.event.senderEmail,
      sender_name: row.event.senderName,
      subject: row.event.subject,
      body_text: row.event.bodyText?.slice(0, 50000) ?? null,
      body_html: row.event.bodyHtml?.slice(0, 100000) ?? null,
      message_id: row.event.messageId,
      in_reply_to: row.event.inReplyTo,
      thread_id: row.event.threadId,
      detected_language: row.detectedLanguage,
      language_confidence: row.languageConfidence,
      is_spam: row.isSpam,
      is_auto_generated: row.isAutoGenerated,
      processing_status: row.processingStatus,
      skip_reason: row.skipReason,
      lead_id: row.leadId,
      received_at: row.event.receivedAt ?? new Date().toISOString(),
    })
    .select('id')
    .maybeSingle();
  return (data?.id as string | null) ?? null;
}

async function markInboundFailed(
  supabase: SupabaseClient,
  inboundId: string | null,
  reason: string
): Promise<void> {
  if (!inboundId) return;
  await supabase
    .from('inbound_emails')
    .update({ processing_status: 'failed', skip_reason: reason, processed_at: new Date().toISOString() })
    .eq('id', inboundId);
}
