/**
 * Spam and auto-generated email filter.
 *
 * Returns a FilterResult explaining whether an inbound email should be
 * processed or skipped, and why.
 */

export interface FilterResult {
  shouldSkip: boolean;
  reason: string | null;
  isSpam: boolean;
  isAutoGenerated: boolean;
}

// ─── No-reply / auto-mailer sender patterns ──────────────────────────────────

const NO_REPLY_PATTERNS = [
  /^no[-._]?reply@/i,
  /^noreply@/i,
  /^do[-._]?not[-._]?reply@/i,
  /^donotreply@/i,
  /^auto[-._]?reply@/i,
  /^mailer[-._]?daemon@/i,
  /^postmaster@/i,
  /^bounce[s]?@/i,
  /^notifications?@/i,
  /^alerts?@/i,
  /^system@/i,
  /^robot@/i,
  /^autoresponder@/i,
  /^delivery[-._]?status@/i,
];

// ─── Subject-line auto-generated indicators ──────────────────────────────────

const AUTO_SUBJECT_PATTERNS = [
  /^automatic reply:/i,
  /^auto[ -]?reply:/i,
  /^out of office:/i,
  /^absent:/i,
  /^delivery status notification/i,
  /^delivery failure/i,
  /^undeliverable:/i,
  /^mail delivery failed/i,
  /^\[?spam\]?/i,
  /^newsletter:/i,
  /^subscription confirmed/i,
];

// ─── Headers / body phrases that indicate auto-generated mail ─────────────────

const AUTO_BODY_PHRASES = [
  'this is an automatic reply',
  'this is an automated message',
  'do not reply to this email',
  'please do not reply',
  'this email was sent automatically',
  'this message was generated automatically',
  'auto-generated email',
  'unsubscribe from this list',
  'you are receiving this email because',
];

// ─── Spam body phrases (basic, not a replacement for SpamAssassin) ────────────

const SPAM_PHRASES = [
  'click here to claim your prize',
  'you have been selected',
  'guaranteed winner',
  'million dollar',
  'nigerian prince',
  'wire transfer request',
  'enlargement',
  'erectile',
  'cialis',
  'viagra',
  'binary options',
  'cryptocurrency investment opportunity',
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function matchesPatternList(value: string, patterns: RegExp[]): boolean {
  return patterns.some((p) => p.test(value));
}

function containsPhrase(text: string, phrases: string[]): boolean {
  const lower = text.toLowerCase();
  return phrases.some((p) => lower.includes(p));
}

// ─── Main export ──────────────────────────────────────────────────────────────

export function filterInboundEmail(params: {
  senderEmail: string;
  subject: string | null;
  bodyText: string | null;
  bodyHtml: string | null;
}): FilterResult {
  const { senderEmail, subject, bodyText, bodyHtml } = params;
  const bodyPlain = bodyText ?? bodyHtml?.replace(/<[^>]+>/g, ' ') ?? '';

  // 1. No-reply / auto-sender address
  if (matchesPatternList(senderEmail, NO_REPLY_PATTERNS)) {
    return { shouldSkip: true, reason: 'no_reply_address', isSpam: false, isAutoGenerated: true };
  }

  // 2. Auto-generated subject
  if (subject && matchesPatternList(subject, AUTO_SUBJECT_PATTERNS)) {
    return { shouldSkip: true, reason: 'auto_generated_subject', isSpam: false, isAutoGenerated: true };
  }

  // 3. Auto-generated body content
  if (containsPhrase(bodyPlain, AUTO_BODY_PHRASES)) {
    return { shouldSkip: true, reason: 'auto_generated_body', isSpam: false, isAutoGenerated: true };
  }

  // 4. Spam content
  if (containsPhrase(bodyPlain, SPAM_PHRASES)) {
    return { shouldSkip: true, reason: 'spam_content', isSpam: true, isAutoGenerated: false };
  }

  // 5. Empty body — nothing to reply to
  if (!bodyPlain.trim()) {
    return { shouldSkip: true, reason: 'empty_body', isSpam: false, isAutoGenerated: false };
  }

  return { shouldSkip: false, reason: null, isSpam: false, isAutoGenerated: false };
}
